### ISSUE TITLE
Need to decide on what to display

### ISSUE THREAD

**Issue by RedPanda4552** [RedPanda4552/Country-Analysis#2]
% Select what data to display
% Appears to be unused at this time.
displayType = menu('Select the data to display', 'Demand v. Production', 'Production Per Source');

This line is intended to let the user choose what data type to view in the graph, but right now the script is just throwing both graphs out. So do we add support for this menu, or drop the menu?

**Comment by Recor** [comment]
I would create the menu, it would be more organized
